{ ... }: {
  imports = [
    ./awesome
    ./bash
    ./development
    ./doom
    ./scripts
    ./yazi
    ./betterlockscreen.nix
    ./btop.nix
    ./fish.nix
    ./git.nix
    ./gtk.nix
    ./kitty.nix
    ./mimeApps.nix
    ./mpv.nix
    ./newsboat.nix
    ./nvim.nix
    ./picom.nix
    ./qt.nix
    ./rofi.nix
    ./virtmanager.nix
    ./zathura.nix
    ./starship.nix
    ./unclutter.nix
    ./xdg.nix
    ./xidlehook.nix
  ];
}
