{ ... }: {
  wayland.windowManager.hyprland = {
    settings = {
      workspace = [
        "workspace = w[t1], gapsout:0, gapsin:0"
        "workspace = w[tg1], gapsout:0, gapsin:0"
        "workspace = f[1], gapsout:0, gapsin:0"
      ];
      windowrule = [
        "float, class:^(net.davidotek.pupgui2)$ #ProtonUp-Qt"
        "float, class:^(yad)$"
        "float, class:^(qt5ct)$"
        "float, class:^(nwg-look)$"
        "float, class:^(org.kde.ark)$"
        "float, class:^(pavucontrol)$"
        "float, class:^(blueman-manager)$"
        "float, class:^(nm-applet)$"
        "float, class:^(nm-connection-editor)$"
        "float, class:^(org.kde.polkit-kde-authentication-agent-1)$"
        "float, class:^(com.obsproject.Studio)$,title:^(Controls)$"
        "float, class:^(qalculate-gtk)$"
        "float, class:^(xdg-desktop-portal-gtk)$"
        "float, class:^(xfce-polkit)$"
        "float, class:^(com.saivert.pwvucontrol)$"
        "float, title:^(Extension: (Bitwarden Password Manager) - Bitwarden — Mozilla Firefox)$"
        "float, class:^(brave-nngceckbapebfimnlniiiahkandclblb-Default)$"
        "float, class:^(chrome-nngceckbapebfimnlniiiahkandclblb-Default)$"
        "float, class:^(lxqt-policykit-agent)$"
        "float, class:^(snx-rs-gui)$"
        "float, class:^(stoken-gui)$"

        ## workspace 1 - development
        "workspace 1, class:^(neovim)$"
        "workspace 1, class:^(lunarvim)$"
        "workspace 1, class:^(nvim)$"
        "workspace 1, class:^(editor)$"
        "workspace 1, class:^(goneovim)$"
        "workspace 1, class:^(Code)$"
        "workspace 1, class:^(emacs)$"
        "workspace 1, class:^(neovide)$"
        "workspace 1, class:^(jetbrains-rider)$"
        "workspace 1, class:^(jetbrains-datagrip)$"
        "workspace 1, class:^(dev.zed.Zed)$"

        ## workspace 2 - toolbox
        "workspace 2, class:^(gnome-boxes)$"
        "workspace 2, class:^(virt-manager)$"
        "workspace 2, class:^(org.keepassxc.KeePassXC)$"
        "workspace 2, class:^(pulsemixer)$"
        "workspace 2, class:^(alsamixer)$"
        "workspace 2, class:^(wdisplays)$"
        "workspace 2, class:^(font-manager)$"
        "workspace 2, class:^(org.qbittorrent.qBittorrent)$"
        "workspace 2, class:^(btop)$"
        "workspace 2, class:^(htop)$"
        "workspace 2, class:^(file-roller)$"
        "workspace 2, class:^(Bitwarden)$"

        ## workspace 4 - web browsing
        "workspace 3, class:^(org.qutebrowser.qutebrowser)$"
        "workspace 3, class:^(org.mozilla.firefox)$"
        "workspace 3, class:^(LibreWolf)$"
        "workspace 3, class:^(org.chromium.Chromium)$"
        "workspace 3, class:^(brave-browser)$"
        "workspace 3, class:^(org.kde.akregator)$"
        "workspace 3, class:^(io.gitlab.news_flash.NewsFlash)$"
        "workspace 3, class:^(liferea)$"
        "workspace 3, class:^(zen)$"
        "workspace 3, class:^(io.github.martinrotter.rssguard)$"

        ## workspace 5 - chatting
        "workspace 4, class:^(gomuks)$"
        "workspace 4, class:^(org.signal.Signal)$"
        "workspace 4, class:^(Ferdium)$"
        "workspace 4, class:^(com.rtosta.zapzap)$"
        "workspace 4, class:^(revolt-desktop)$"
        "workspace 4, class:^(Element)$"

        ## workspace 6 - music & audio
        "workspace 5, class:^(lollypop)$"
        "workspace 5, class:^(Audacity)$"
        "workspace 5, class:^(Ardour)$"
        "workspace 5, class:^(carla)$"
        "workspace 5, class:^(carla-control)$"
        "workspace 5, class:^(hydrogen)$"
        "workspace 5, class:^(guitarix)$"
        "workspace 5, class:^(lsp-plugins)$"
        "workspace 5, class:^(QjackCtl)$"
        "workspace 5, class:^(org.rncbc.qpwgraph)$"
        "workspace 5, class:^(soundconverter)$"
        "workspace 5, class:^(kid3-qt)$"
        "workspace 5, class:^(com.github.wwmm.easyeffects)$"
        "workspace 5, class:^(de.haeckerfelix.Shortwave)$"
        "workspace 5, class:^(com.github.Bleuzen.FFaudioConverter)$"
        "workspace 5, class:^(flacon)$"
        "workspace 5, class:^(org.gnome.Podcasts)$"
        "workspace 5, class:^(org.kde.kid3)$"

        ## workspace 7 - video
        "workspace 6, class:^(pitivi)$"
        "workspace 6, class:^(org.kde.kdenlive)$"
        "workspace 6, class:^(mpv)$"
        "workspace 6, class:^(vlc)$"
        "workspace 6, class:^(com.obsproject.Studio)$"
        "workspace 6, class:^(fr.handbrake.ghb)$"

        ## workspace 8 - graphics
        "workspace 7, class:^(org.inkscape.Inkscape)$"
        "workspace 7, class:^(Gimp-2.10)$"
        "workspace 7, class:^(krita)$"
        "workspace 7, class:^(darktable)$"
        "workspace 7, class:^(org.kde.digikam)$"
        "workspace 7, class:^(blender)$"

        ## workspace 9 - office
        "workspace 8, class:^(libreoffice-writer)$"
        "workspace 8, class:^(libreoffice-calc)$"
        "workspace 8, class:^(libreoffice-impress)$"
        "workspace 8, class:^(libreoffice-base)$"
        "workspace 8, class:^(libreoffice-draw)$"
        "workspace 8, class:^(libreoffice-math)$"
        "workspace 8, class:^(libreoffice-startcenter)$"
        "workspace 8, class:^(GeoGebra)$"
        "workspace 8, class:^(Notesnook)$"
        "workspace 8, class:^(org.pwmt.zathura)$"
        "workspace 8, class:^(com.github.xournalpp.xournalpp)$"
        "workspace 8, class:^(com.github.flxzt.rnote)$"
        "workspace 8, class:^(net.cozic.joplin_desktop)$"
        "workspace 8, class:^(com.github.johnfactotum.Foliate)$"
        "workspace 8, class:^(evince)$"
        "workspace 8, class:^(obsidian)$"
        "workspace 8, class:^(ONLYOFFICE Desktop Editors)$"

        ## workspace 10 - games
        "workspace 9, class:^(org.libretro.RetroArch)$"
        "workspace 9, class:^(com.github.tkashkin.gamehub)$"
        "workspace 9, class:^(xonotic-linux64-sdl)$"
        "workspace 9, class:^(pyrogenesis)$"
        "workspace 9, class:^(wesnoth)$"
        "workspace 9, class:^(steam)$"
        "workspace 9, class:^(Minetest)$"
        "workspace 9, class:^(org.prismlauncher.PrismLauncher)$"
        "workspace 9, class:^(net.lutris.Lutris)$"
        "workspace 9, class:^(es-de)$"
        "workspace 9, class:^(xemu)$"
        "workspace 9, class:^(duckstation-qt)$"
        "workspace 9, class:^(pcsx2-qt)$"
        "workspace 9, class:^(info.cemu.Cemu)$"
        "workspace 9, class:^(org.ppsspp.PPSSPP)$"
        "bordersize 0, floating:0, onworkspace:w[t1]"
        "rounding 0, floating:0, onworkspace:w[t1]"
        "bordersize 0, floating:0, onworkspace:w[tg1]"
        "rounding 0, floating:0, onworkspace:w[tg1]"
        "bordersize 0, floating:0, onworkspace:f[1]"
        "rounding 0, floating:0, onworkspace:f[1]"
      ];
    };
  };
}
