#!/usr/bin/env bash

# ***This script was made by Lian Dynn (Drake)***
#  - Description: A simple rofi script to set the wallpaper on X
#  - Dependencies: rofi, fd, xwallpaper, betterlockscreen

# Directory containing wallpapers
walldir="$XDG_PICTURES_HOME/Wallpapers"
restorescript="$HOME/.wm_restorewall"

# Define wallpaper options for xwallpaper
option1="Fill"
option2="Center"
option3="Tile"
option4="Maximize"
option5="Stretch"
options="$option1\n$option2\n$option3\n$option4\n$option5"

# Prompt user to select a wallpaper
ls_command=$(command -v ls)
cd "$walldir" || exit 1
wallpaper=$($ls_command | sort -n | rofi -dmenu -i -p " 󰋩 Select a wallpaper ") # main prompt
if [ -z "$wallpaper" ]; then
    exit 0
fi

# Store the selected wallpaper
chosenwall="$wallpaper"

# Function to generate a script to restore wallpaper
generateScript() {
    echo "#!/usr/bin/env bash" > "$restorescript"
    echo "xwallpaper $1 \"$walldir/$chosenwall\"" >> "$restorescript"
    chmod +x "$restorescript"
}

action=$(echo -e "$options" | rofi -dmenu -i -p "  Chose the format ") # options prompt
case "$action" in
    $option1*)
        xwallpaper --zoom "$chosenwall"
        generateScript "--zoom"
        betterlockscreen -u "$chosenwall" -q &
        ;;
    $option2*)
        xwallpaper --center "$chosenwall"
        generateScript "--center"
        betterlockscreen -u "$chosenwall" -q &
        ;;
    $option3*)
        xwallpaper --tile "$chosenwall"
        generateScript "--tile"
        betterlockscreen -u "$chosenwall" -q &
        ;;
    $option4*)
        xwallpaper --maximize "$chosenwall"
        generateScript "--maximize"
        betterlockscreen -u "$chosenwall" -q &
        ;;
    $option5*)
        xwallpaper --stretch "$chosenwall"
        generateScript "--stretch"
        betterlockscreen -u "$chosenwall" -q &
        ;;
esac
