#!/usr/bin/env bash

# ***This script was made by Lian Dynn (Drake)***
#  - Description: A simple power menu rofi script
#  - Dependencies: rofi, power-profiles-daemon, betterlockscreen

#######################
## Main manu options ##
#######################
option1="  Logout"
option2="  Reboot"
option3="  Power off"
option4="󰒲  Suspend"
option5="  Lock"
option6="  Change power profile"
option7="󱎘  Exit"
options="$option1\n$option2\n$option3\n$option4\n$option5\n$option6\n$option7"

####################################
## Power profiles submenu options ##
####################################
pwr1="󰓅 Performance"
pwr2="󰾅 Balanced"
pwr3="󰾆 Power Saver"
pwr4=" Cancel"
pwrs="$pwr1\n$pwr2\n$pwr3\n$pwr4"

## This variable will store the current power profile
currentpwr=$(powerprofilesctl get)

## Ask yes/no for action confirmation
confirm_action() {
    local prompt="$1"
    echo -e "  Yes\n  No" | rofi -dmenu -l 2 -i -p "$prompt" | grep -q "  Yes"
}

####################
# Main Script Flow #
####################

action=$(echo -e "$options" | rofi -dmenu -i -p "   Power Options ");

if [ -z "$action" ]; then
    exit 0
fi

case "$action" in
        "$option1")
        if confirm_action "   Are you sure you want to logout? "; then
            loginctl kill-session self
        fi
        ;;
    "$option2")
        if confirm_action "   Are you sure you want to reboot? "; then
            systemctl reboot
        fi
        ;;
    "$option3")
        if confirm_action "   Are you sure you want to power off? "; then
            systemctl poweroff
        fi
        ;;
    "$option4")
        systemctl suspend
        ;;
    "$option5")
        betterlockscreen -l
        ;;
    "$option6")
        if [ "$currentpwr" = "performance" ]; then
            currentpwr="$pwr1"
        elif [ "$currentpwr" = "balanced" ]; then
            currentpwr="$pwr2"
        elif [ "$currentpwr" = "power-saver" ]; then
            currentpwr="$pwr3"
        fi

        pwraction=$(echo -e "$pwrs" | rofi -dmenu -i -p "   Power Profile Menu - Currently set to: $currentpwr ") 

        case "$pwraction" in
            "$pwr1")
                if [ "$currentpwr" = "$pwr1" ]; then
                    notify-send "The power profile is already set to performance"
                    exit 1
                else
                    powerprofilesctl set performance && notify-send "Power profile switched to performance"
                fi
                ;;
            "$pwr2")
                if [ "$currentpwr" = "$pwr2" ]; then
                    notify-send "The power profile is already set to balanced"
                    exit 1
                else
                    powerprofilesctl set balanced && notify-send "Power profile switched to balanced"
                fi
                ;;
            "$pwr3")
                if [ "$currentpwr" = "$pwr3" ]; then
                    notify-send "The power profile is already set to power saver"
                    exit 1
                else
                    powerprofilesctl set power-saver && notify-send "Power profile switched to power saver"
                fi
                ;;
            "$pwr4")
                exit 0
        esac
        ;;
    "$option7")
        exit 0
        ;;
esac
