#!/usr/bin/env bash

# rs_wall - A simple wallpaper picker menu script for fuzzel
# Author: Lian Dynn
# Dependencies: fuzzel, swaybg

############################
# Configuration Parameters #
############################
walldir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers"
mkdir -p "$walldir"

####################
# Main Script Flow #
####################
ls_command=$(command -v ls)
cd "$walldir" || exit 1
wallpaper=$("$ls_command" | sort -n | fuzzel --dmenu -l 5 -i -p "[󰋩 Wallpaper Selector]  ")
if [ -n "$wallpaper" ]; then
    if [[ "$wallpaper" == *.jpg ]]; then
        rm -f "$HOME/.config/sway/wallpaper/"*
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/background.jpg"
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/locked.jpg"
        swaymsg output \* bg "$HOME/.config/sway/wallpaper/background.jpg" fill
    elif [[ "$wallpaper" == *.png ]]; then
        rm -f "$HOME/.config/sway/wallpaper/"*
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/background.png"
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/locked.png"
        swaymsg output \* bg "$HOME/.config/sway/wallpaper/background.png" fill
    fi
else
    exit 0
fi
exit 0
