#!/usr/bin/env bash

# rs_wall - A simple screenshot menu script for rofi/dmenu/wofi/fuzzel
# Author: Lian Dynn
# Dependencies: fuzzel, hyprpaper

############################
# Configuration Parameters #
############################
walldir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers" # wallpapers folder, change it to yours
destdir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/wall"
mkdir -p "$walldir" "$destdir"

####################
# Main Script Flow #
####################
ls_command=$(command -v ls)
cd "$walldir" || exit 1
wallpaper=$("$ls_command" | sort -n | fuzzel --dmenu -l 5 -i -p "[󰋩 Wallpaper Selector]  ")
if [ -n "$wallpaper" ]; then
    cp "$wallpaper" "$destdir/wall.png"
    cp "$wallpaper" "$destdir/lock.png"
    pidof hyprpaper && pkill hyprpaper
    sleep 0.5
    hyprpaper &
    disown
else
    exit 0
fi
exit 0
