#!/usr/bin/env bash

# rs_wifi - A simple WiFi menu script for fuzzel
# Author: Lian Dynn
# Dependencies: fuzzel, NetworkManager, libnotify (notify-send)

############################
# Configuration Parameters #
############################

# Main menu options
option1="  Turn on WiFi"
option2="  Turn off WiFi"
option3="󱛅  Disconnect WiFi"
option4="󱛃  Connect WiFi"
option5="󱛆  Setup captive portal"
option6="  Exit"
options="$option1\n$option2\n$option3\n$option4\n$option5\n$option6"

# WiFi interface information
wifi_info=$(nmcli dev | awk '/wifi/ {print $1,$3; exit}')
read -r wlan constate <<< "$wifi_info"

########################
# Function Definitions #
########################
# Turn off WiFi
turnoff() {
    nmcli radio wifi off
    if [ $? -eq 0 ]; then
        notify-send "Wifi Menu" "WiFi has been turned off"
    else
        notify-send "Wifi Menu" "Failed to turn off WiFi"
    fi
}

# Turn on WiFi
turnon() {
    nmcli radio wifi on
    if [ $? -eq 0 ]; then
        notify-send "Wifi Menu" "WiFi has been turned on"
    else
        notify-send "Wifi Menu" "Failed to turn on WiFi"
    fi
}

# Disconnect from WiFi
disconnect() {
    if [ "$constate" = "disconnected" ]; then
        notify-send "Wifi Menu" "WiFi is already disconnected"
    elif [ "$constate" = "connected" ]; then
        nmcli device disconnect "$wlan"
        if [ $? -eq 0 ]; then
            notify-send "Wifi Menu" "WiFi has been disconnected"
        else
            notify-send "Wifi Menu" "Failed to disconnect WiFi"
        fi
    else
        notify-send "Wifi Menu" "Unknown WiFi state"
    fi
}

# Connect to a WiFi network
connect() {
    notify-send "Wifi Menu" -t 5000 "Scanning networks..."
    nmcli dev wifi rescan
    wifinet=$(nmcli -f BSSID,SSID,BARS,SECURITY dev wifi list | sed -n '1!p' | fuzzel --dmenu -i -l 10 -p "[  Select a Wifi Network]  ");
    if [ -z "$wifinet" ]; then
        exit 0
    fi
    bssid=$(echo "$wifinet" | awk '{print $1}')
    ssid=$(echo "$wifinet" | awk '{print $2}')
}

# Prompt for WiFi password
password() {
    if nmcli connection show | awk -v ssid="$ssid" '$1 == ssid {found=1} END {exit !found}'; then
        pass=""
    elif nmcli -f BSSID,SECURITY dev wifi list | grep -w "$bssid" | awk '{print $2}' | grep -q -- "--"; then
        pass=""
    else
        pass=$(fuzzel --dmenu -l 0 --password -p "[Enter Password  ]  " );
        if [ -z "$pass" ]; then
            exit 0
        fi
    fi
}

# Execute WiFi connection
action() {
    if [ -n "$pass" ]; then
        nmcli dev wifi connect "$bssid" password "$pass"
    else
        nmcli dev wifi connect "$bssid"
    fi
    if [ $? -eq 0 ]; then
        notify-send "Wifi Menu" "Connected to $ssid"
    else
        notify-send "Wifi Menu" "Failed to connect to $ssid"
    fi
}

####################
# Main Script Flow #
####################

cases=$(echo -e "$options" | fuzzel --dmenu -i -l 6 -p "[  Wifi Settings]  " ) # main menu prompt
if [ -z "$cases" ]; then
    exit 0
fi

case "$cases" in
    "$option1")
        turnon
        ;;
    "$option2")
        turnoff
        ;;
    "$option3")
        disconnect
        ;;
    "$option4")
        if connect; then
            if password; then
                action
            fi
        fi
        ;;
    "$option5")
        ${BROWSER:-xdg-open} http://networkcheck.kde.org
        ;;
    "$option6")
        exit 0
        ;;
esac
