#!/usr/bin/env bash
# rs_wall - A wallpaper selector using fzf with image previews
# Author: Lian Dynn
# Dependencies: fzf, kitty (with icat), hyprpaper
############################
# Configuration Parameters #
############################
walldir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers" # wallpapers folder, change it to yours
destdir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/wall"
mkdir -p "$walldir" "$destdir"

####################
# Main Script Flow #
####################
cd "$walldir" || exit 1

# Use fzf with kitty icat preview
wallpaper=$(ls -1 | sort -n | fzf \
    --prompt="[󰋩 Wallpaper Selector]  " \
    --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}' \
    --preview-window=right:50% \
    --height=100% \
    --border=rounded \
    --layout=reverse)

if [ -n "$wallpaper" ]; then
    cp "$wallpaper" "$destdir/wall.png"
    cp "$wallpaper" "$destdir/lock.png"
    pidof hyprpaper && pkill hyprpaper
    sleep 0.5
    hyprpaper &
    disown
else
    exit 0
fi

exit 0
