#!/bin/bash

# Grab monitor status (varies with the machine)
docked_main=$(cat /sys/class/drm/card1-DP-3/status)
docked_sec=$(cat /sys/class/drm/card1-DP-4/status)
external_usbc=$(cat /sys/class/drm/card1-DP-1/status)
external_hdmi=$(cat /sys/class/drm/card1-HDMI-A-1/status)

# If both monitors are connected
if [ "$docked_main" = "connected" ] && [ "$external_usbc" = "connected" ]; then
    xrandr --output eDP1 --off \
           --output DP2-1 --primary --mode 1920x1080 --rate 100.00 --pos 0x0 --rotate normal \
           --output DP1 --mode 1280x1024 --pos 1920x0 --rate 75.02 --rotate normal
# If I'm with my work dock
elif [ "$docked_main" = "connected" ] && [ "$docked_sec" = "connected" ]; then
    xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal \
	    --output DP2-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
	    --output DP2-2 --mode 1920x1080 --pos 3840x0 --rotate left
# If only HDMI is connected
elif [ "$external_hdmi" = "connected" ]; then
    xrandr --output eDP1 --primary --auto \
           --output HDMI2 --auto --scale-from 1920x1080 --same-as eDP-1
# If only DP is connected
elif [ "$external_usbc" = "connected" ]; then
    xrandr --output eDP1 --primary --auto \
           --output DP1 --auto --scale-from 1920x1080 --same-as eDP-1
else
    # Single internal monitor setup
    xrandr --output eDP1 --primary --auto && \
    xrandr --output HDMI2 --off \
        --output HDMI1 --off \
        --output DP1 --off \
        --output DP2 --off \
        --output DP2-1 --off \
        --output DP2-2 --off \
        --output DP2-3 --off
fi
